name: test

on: [push]

jobs:
    seth:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.2
            - run: pnpm i --frozen-lockfile
            - run: pnpm test
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  ROPSTEN_PRIVATE_KEY: ${{ secrets.ROPSTEN_PRIVATE_KEY }}
